import type { IntentDef } from "./types";

/**
 * Intents answered from the student's own analytics (kind: "personal") or that
 * are purely conversational (kind: "smalltalk"). See responder.ts for how each
 * id turns into a reply.
 */
export const intents: IntentDef[] = [
  {
    id: "my_weak_areas",
    kind: "personal",
    questions: [
      "what are my weak areas",
      "which topics am i weak in",
      "where am i struggling",
      "what do i need to improve",
      "show my weakest subjects",
      "topics i need to work on",
      "which topics should i focus on",
      "what am i bad at",
      "list my weak topics",
      "where do i lose marks",
    ],
  },
  {
    id: "my_strengths",
    kind: "personal",
    questions: [
      "what are my strengths",
      "which topics am i good at",
      "what is my best subject",
      "what am i strong in",
      "show my strongest areas",
      "where do i perform well",
      "what am i good at",
      "which subjects am i confident in",
    ],
  },
  {
    id: "my_progress",
    kind: "personal",
    questions: [
      "how am i doing",
      "show my progress",
      "give me a summary of my performance",
      "how is my preparation going",
      "am i improving",
      "am i ready for placements",
      "what is my readiness score",
      "how prepared am i",
      "my overall performance",
      "analyse my performance",
      "how have i performed",
      "how did i perform overall",
      "how am i performing so far",
      "how have i been doing lately",
      "give me an overview of my results",
    ],
  },
  {
    id: "my_aptitude",
    kind: "personal",
    questions: [
      "what is my aptitude score",
      "how did i do in aptitude tests",
      "my mock test results",
      "my last aptitude test score",
      "show my aptitude performance",
      "how many aptitude tests have i taken",
    ],
  },
  {
    id: "my_interview",
    kind: "personal",
    questions: [
      "my interview feedback",
      "how did my mock interview go",
      "what are my interview scores",
      "what did my interview report say",
      "show my mock interview performance",
      "how is my communication score",
      "feedback on my last interview",
      "what did the interviewer say about me",
    ],
  },
  {
    id: "my_techquiz",
    kind: "personal",
    questions: [
      "my tech quiz results",
      "how did i do in tech practice",
      "my technology quiz performance",
      "what is my score in java quiz",
      "show my tech practice history",
    ],
  },
  {
    id: "next_steps",
    kind: "personal",
    questions: [
      "what should i study next",
      "what should i practice today",
      "recommend what i should practise",
      "give me a plan based on my performance",
      "suggest my next steps",
      "what should i do next to improve",
      "personalised study plan for me",
      "what to focus on this week",
    ],
  },
  {
    id: "my_resources",
    kind: "personal",
    questions: [
      "recommend resources for my weak topics",
      "study material for my weak areas",
      "where can i learn my weak topics",
      "links to learn what i am weak in",
      "suggest tutorials for my weak subjects",
      "resources to improve my weak areas",
      "how can i learn my weak subjects",
      "tutorials for topics i am weak in",
      "where to study what i am weak at",
      "learning links for my weak topics",
    ],
  },
  // ── small talk ───────────────────────────────────────
  {
    id: "greeting",
    kind: "smalltalk",
    questions: ["hello", "hi there", "hey", "good morning", "good evening", "hi bot", "hello assistant"],
  },
  {
    id: "thanks",
    kind: "smalltalk",
    questions: ["thanks", "thank you", "thank you so much", "thanks a lot", "that was helpful", "great thanks"],
  },
  {
    id: "goodbye",
    kind: "smalltalk",
    questions: ["bye", "goodbye", "see you later", "good night", "talk to you later"],
  },
  {
    id: "identity",
    kind: "smalltalk",
    questions: [
      "who are you",
      "what is your name",
      "are you a bot",
      "are you chatgpt",
      "are you an ai",
      "which ai model are you",
      "do you use openai",
      "are you a robot",
      "are you human",
      "are you a real person",
      "who made you",
      "what are you",
    ],
  },
];

/**
 * Out-of-scope messages. They are never answered; the trainer uses them to
 * learn how high a similarity score must be before an answer is trustworthy.
 * Includes "tough" ones that share words (time, score, interview) with real topics.
 */
export const outOfScope: string[] = [
  "what is the weather today",
  "who won the cricket match yesterday",
  "tell me a joke",
  "best pizza near me",
  "what is the capital of france",
  "how to cook pasta",
  "recommend a good movie",
  "what is the bitcoin price",
  "who is the prime minister",
  "translate good morning to spanish",
  "play some music",
  "what is the meaning of life",
  "how tall is mount everest",
  "latest smartphone launch",
  "football score today",
  "what time is it right now",
  "how do i lose weight fast",
  "which movie should i watch tonight",
  "who is the richest person in the world",
  "how to train a puppy",
  "what is the speed of light",
  "write a poem about the ocean",
  "how do i get a girlfriend",
  "best places to visit in goa",
  "how to fix a leaking tap",
  "when is the next holiday",
  "how many players are in a football team",
  "what is the score of the ipl match",
  "which car should i buy",
  "tell me about your day",
  "tell me a bedtime story",
  "price of petrol today",
  "how is the share market performing",
  "what is the gold rate",
  "who is your favourite actor",
  "what is the population of china",
  "how do i make tea",
  "sing me a song",
  "what is the tallest mountain",
  "give me a recipe for biryani",
  "how many days in a year",
  "what is the distance between earth and moon",
  "is it going to be sunny this weekend",
  "how do i grow tomatoes at home",
  "who invented the telephone",
  "what is the currency of japan",
  "how to get a driving licence",
  "tell me about the history of rome",
  "best smartphone under twenty thousand",
  "how do i pair bluetooth headphones",
  "what movies are releasing this friday",
  "what should i cook for dinner",
  "how to remove a stain from a shirt",
  "tell me interesting facts about space",
  "which is the biggest ocean",
  "when is diwali this year",
  "how to learn to swim",
  "what are the symptoms of fever",
  "how to book a train ticket",
  "who is the captain of the indian team",
  "what is the price of a laptop",
  "how many calories in a banana",
  "explain the plot of a famous movie",
  "can you draw me a picture",
  "what is your favourite colour",
  "do you like pizza",
  "what is the time in london",
  "how do i start a youtube channel",
  "how to make a paper plane",
  "what is inflation rate this year",
  "tell me about elon musk",
  "how do i get a visa for the usa",
  "how is my horoscope today",
  "what shall i wear to a wedding",
  "how do i learn guitar",
  "where can i buy shoes online",
  "how many continents are there",
  "who wrote romeo and juliet",
  "what is the boiling point of water",
  "how do vaccines work",
  "how far is the sun",
  "how is the stock market today",
  "tell me something interesting",
  "what is happening in the news",
  "who will win the election",
  "give me a fun fact",
  "what did you eat today",
];
